default:
  #Service name of Your app, it can not contain airflow in its name
  serviceName: myService
  owner: threeventures
  # AWS Certificate Manager (ACM) to allow https
  certificate:
  timeZone: US/Pacific
  www:
    wwwAdmin: airflow-admin
    wwwPassword: 12345678!@#$%
    wwwEmail: example@example.com

  github:
    fullRepositoryName:
    location:
    codestarArn:
    branch: example

  service:
    logGroupName: airflow/ecs/fargate
    cidrBlock: 10.0.0.0
    baseUrl: http://localhost:8080
    port: 80
    scheduler:
      cpu: 1024
      memory: 2048
      desiredCount: 1
      autoscaling:
        maxCapacity: 1
        minCapacity: 1
        cpu:
          target: 70
          scaleInCooldown: 180
          scaleOutCooldown: 60
        memory:
          target: 90
          scaleInCooldown: 180
          scaleOutCooldown: 60
    webserver:
      port: 8080
      cpu: 1024
      memory: 2048
      desiredCount: 1
      autoscaling:
        maxCapacity: 1
        minCapacity: 1
        cpu:
          target: 60
          scaleInCooldown: 180
          scaleOutCooldown: 60
        memory:
          target: 80
          scaleInCooldown: 180
          scaleOutCooldown: 60
    workers:
      port: 8793
      cpu: 2048
      memory: 4096
      desiredCount: 1
      autoscaling:
        maxCapacity: 2
        minCapacity: 1
        cpu:
          target: 70
          scaleInCooldown: 60
          scaleOutCooldown: 120
        memory:
          target: 70
          scaleInCooldown: 60
          scaleOutCooldown: 120

  publicSubnet:
    1:
      cidrBlock: 10.0.1.0/24
      availabilityZone: a
    2:
      cidrBlock: 10.0.2.0/24
      availabilityZone: b
    3:
      cidrBlock: 10.0.3.0/24
      availabilityZone: c

  whitelistedIPs:
    - 0.0.0.0/0

  metadataDb:
    instanceType: db.t3.micro
    port: 5432
    dbName: airflow
    engine: postgres
    engineVersion: 13.7
    family: postgres13
    deletionProtection: false
    enableIAMDatabaseAuthentication: true
    allocatedStorage: 20
    parameters:
      maxConnections: 100

  celeryBackend:
    port: 6379
    azMode: single-az
    engine: redis
    engineVersion: 6.2
    autoMinorVersionUpgrade: true
    instanceType: cache.t3.micro
    numNodes: 1

  ecr:
    imagesLifecycleCount: 3

  cloudwatch:
    ecsLogGroup:
      retention: 14
